name: Bug Report
description: Report a bug or issue with OrcaSlicer
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        # Important Notice
        **This is an unofficial fork of OrcaSlicer. Please do NOT report bugs found here to the official OrcaSlicer repository.**

        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched the existing issues and this bug has not been reported before
          required: true
        - label: I understand this is an unofficial fork and will not report this issue to the official OrcaSlicer
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead.
      placeholder: What happened instead?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: OrcaSlicer Version
      description: What version of OrcaSlicer are you running? (Check Help > About)
      placeholder: "e.g., 2.3.2-Nanashi+abc1234"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows 10
        - Windows 11
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux (Ubuntu/Debian)
        - Linux (Fedora)
        - Linux (Arch)
        - Linux (Flatpak)
        - Linux (Other)
    validations:
      required: true

  - type: input
    id: printer
    attributes:
      label: Printer Model
      description: What printer are you using?
      placeholder: "e.g., Bambu Lab X1C, Prusa MK4, Ender 3"

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (3MF files, G-code, settings, etc.)
